name: Deploy AKS with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.5

      - name: Configure Azure credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          
      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve

      - name: Set up Kubeconfig
        run: |
          az aks get-credentials --resource-group rg-aks-cluster --name my-aks-cluster --admin
